### ISSUE TITLE
AC 1.5.5 Create Bill/Expense pulls Customer names only

### ISSUE THREAD

**Issue by tjlabais** [wp-erp/wp-erp#879] opened 2019-10-04 08:30 UTC
![bill01](https://user-images.githubusercontent.com/1410197/66192855-f4b49f80-e6c3-11e9-9583-0b1602274f88.jpg)
-------------------------------------------------------------------------
![bill02](https://user-images.githubusercontent.com/1410197/66192974-36dde100-e6c4-11e9-914b-f27ef771ecc7.jpg)

**Comment by itowhid06** [comment] 2019-10-04 08:40
Hello @tjlabais ,

Bill/Expense can be made against any customer, vendor or employee. Invoices can be created only against customers and Purchases can be created only agains vendors. 

Thanks

**Comment by tjlabais** [comment] 2019-10-04 09:19
**Only customers are accessible in PAY TO. Vendors and Employees don't show up.**

![bill04](https://user-images.githubusercontent.com/1410197/66196104-8cb58780-e6ca-11e9-9133-5f70903c61a4.jpg)
**Fig.1. searching for vendor**

![bill05](https://user-images.githubusercontent.com/1410197/66196396-0483b200-e6cb-11e9-966c-3c144f53b05c.jpg)
**Fig.2. searching employee**

**Comment by tjlabais** [comment] 2019-10-16 05:50
@itowhid06 can you help include this fix in 1.5.6? Would appreciate it very much; so, we can migrate our expenses from the old 1.4.6. Thanks

**Comment by thebengalboy** [comment] 2019-10-24 05:20
Hello @tjlabais 

We have checked it in different ways and found both the Customer, Vendor and Employee listed. So, the issue is not with the core. Reference screenshot: https://d.pr/i/VC9whW

However, if you get customers only on that list, then maybe there is any other problem happening on your site, which you can get help from our support team :)

Thanks

**Comment by tjlabais** [comment] 2019-10-24 06:47
I have tested this both to a fresh install v.1.5.5 and to the migrated version. Both exhibit the same problem.

**Comment by tjlabais** [comment] 2019-10-24 06:48
@thebengalboy

**Comment by tjlabais** [comment] 2019-10-24 07:03
**Okay, I deleted some customers from 25 entities to 5, and the rest will show: customer, employee and vendor. Try putting in more than one page of customers to replicate the problem. **
![expense01](https://user-images.githubusercontent.com/1410197/67461233-74081400-f66f-11e9-9c87-9c67b20a0ce6.jpg)

**Comment by thebengalboy** [comment] 2019-10-28 07:05
Hello @tjlabais 

We have checked it with more than 25 entries for both the customer, employee, and vendor but unfortunately, it's working perfectly to us!

However, if you can contact our support center with your site details, we can debug the issue on your site why this is happening. Thanks

**Comment by tjlabais** [comment] 2019-10-28 10:45
Steps to replicate:
1. Fresh wordpress install
2. install wp erp plugin
3. install pdf plugin
4. did not add any employee during wp erp setup
5. install HRM, CRM, AC -> no Project Manager
6. encode 21 customers straight in AC module
7. encode 21 vendors straight in AC module
8. no CRM companies encoded
9. create a new expense -> only vendors are pulled and can not search customers

somehow the method of encoding the data affect this bug. in my live data, hundreds of companies were encoded first before the vendors.

if I encode it alternately customer, vendor, employee, the search function works.

**Comment by thebengalboy** [comment] 2020-09-25 04:23
Hello @tjlabais 

This should be resolved by now.

Thanks

**Closed by thebengalboy** 2020-09-25 04:23 UTC
Labels: AC
