### ISSUE TITLE
Importing CSV doesn't automatically update "Department" and "Designation" for every employees

### ISSUE THREAD

**Issue by saiftheboss7** [wp-erp/wp-erp#917] opened 2019-11-08 05:41 UTC
Importing CSV doesn't automatically update "Department" and "Designation" for every employees.

Test Scenario: I exported 50+ Employees (via the ERP export tool). And gave each employee the same designation and imported the new file. ERP doesn't update the employee designation nor department.

**Comment by thebengalboy** [comment] 2020-01-06 08:15
Hello @saiftheboss7 

We tried with multiple CSV file but unfortunately, we were unable to reproduce the issue as you mentioned. Can you please provide the CSV that you have tried to import? It may help us to reproduce the problem.

Thanks

**Comment by thebengalboy** [comment] 2020-01-31 03:56
Hello @saiftheboss7 

We are closing this issue considering not a bug in the core. If you face the same further, please feel free to contact our support center.

Thanks

**Closed by thebengalboy** 2020-01-31 03:56 UTC
