### ISSUE TITLE
AC 1.5.4 Edit Sales Invoice will lead to creation of 3 transaction entries

### ISSUE THREAD

**Issue by tjlabais** [wp-erp/wp-erp#865] opened 2019-09-26 09:53 UTC
**Normally, if there are changes in the sales invoice, we just void an invoice (one entry) and create a new invoice (second entry). However, the edit function of AC 1.5.4 produce 3 entries**

![edit01](https://user-images.githubusercontent.com/1410197/65678781-8437ce00-e086-11e9-8a6f-fc8e1a2f6726.JPG)

**Comment by thebengalboy** [comment] 2019-10-01 09:46
Hello @tjlabais 

This is an intentional feature/behavior actually. I know it's kinda confusing but let me explain the whole scenario.

Suppose, you have created an invoice on September 25th, with 50$ amount. September is gone and you have closed your calculation for September. You took the ledger report as well.

Today, 1st October, you realized, the invoice was wrong. It would be 75$, not 50. What would you do? If you void the invoice, the whole calculation will be messed up and that won't be reflected on your September closing balance. Right?

So, you can edit the invoice in those cases. If you edit the invoice, it creates another one with the same amount as just the opposite transection, debit or credits, and closes all these two. After then, it creates a new one, with the edited information, say the amount is 75$ now.

Void has a different use case, but sometimes it requires to edit an invoice as well.

You can still share your thoughts on this here but I'm closing the issue considering this is not a bug or plugin issue.

Thanks

**Closed by thebengalboy** 2019-10-01 09:46 UTC
