### ISSUE TITLE
CRM 1.5.5 Export Company did not include custom field

### ISSUE THREAD

**Issue by tjlabais** [wp-erp/wp-erp#909] opened 2019-10-28 04:08 UTC
**see selected fields for export and see CSV data exported below: **
![export01](https://user-images.githubusercontent.com/1410197/67651314-63131780-f97b-11e9-8130-22d64013dc36.JPG)
![export02](https://user-images.githubusercontent.com/1410197/67651321-6908f880-f97b-11e9-9799-18faa1e56135.JPG)

**export contact includes custom field however associated company is not included so the list is not workable**

**Comment by makdhk** [comment] 2020-01-30 08:08
Hi, 

As per our implementation if any of the field does not have any data that column will not appear in CSV. Can you confirm whether Currency and Events data were available? 

Thanks

**Comment by thebengalboy** [comment] 2020-10-18 12:08
Hello @tjlabais 

As we were not able to reproduce the issue and you have not replied further, we are closing the issue for now. However, please check the same as @makdhk said. If you get the same problem again, feel free to reopen the issue.

Thanks

**Closed by thebengalboy** 2020-10-18 12:08 UTC
