### ISSUE TITLE
Deals

### ISSUE THREAD

**Issue by monogios** [wp-erp/wp-erp#298] opened 2016-09-15 13:32 UTC
CRM needs a Deals sections so it can be considered as a CRM.

**Comment by codeshah** [comment] 2016-09-15 16:10
Hello @monogios,

We are already working on the deals feature and it is close to the beta release. All of our paid customers have access to our beta testing program. So if you have purchased any add-on from us, please send an email to support@wperp.com. When it is ready for testing, I will send you via reply.

**Comment by tareq1988** [comment] 2016-12-22 15:55
Duplicate of #151. The add-on has been created and is in testing.

**Closed by tareq1988** 2016-12-22 15:55 UTC
Labels: Add-On, CRM, [Status] In Progress
