### ISSUE TITLE
No Data View for Transfer Money Transaction

### ISSUE THREAD

**Issue by mhmdadel** [wp-erp/wp-erp#936] opened 2019-12-13 19:23 UTC
When I was reviewing the Cash Movements
I found that there entries with no data just number as screenshot below
https://prntscr.com/qaibuy
I clicked on it to view, I find that is a "Transfer Transaction" but no data appears, All transfer transaction when viewing them appears the same view
https://prntscr.com/qaic5a

**Comment by emran-wedevs** [comment] 2020-09-23 05:44
We could not reproduce the issue. It seems okay so far. So, we are considering to close the issue here. If you face/find the same problem again, feel free to reopen it.
Thanks

**Closed by emran-wedevs** 2020-09-23 05:44 UTC
Labels: AC
