### ISSUE TITLE
Feature Suggestion: Multi currency in Accounting 

### ISSUE THREAD

**Issue by shawon786** [wp-erp/wp-erp#601] opened 2018-01-25 08:08 UTC
Multi-currency feature to the
accounting module for your ERP. 
We use both KES and USD
and would love to handle both currencies and any future currencies that may
come.

**Comment by thebengalboy** [comment] 2019-12-03 10:34
Duplicate of https://github.com/wp-erp/wp-erp/issues/266

**Closed by thebengalboy** 2019-12-03 10:34 UTC
Labels: AC, Features, Pro
